import json
import os
from typing import Dict, Optional

from ...utils.text import to_titlecase_no_space, underscore_to_titlecase_main


def create_files(
    base_path: str,
    doc_name: str,
    doc_id: str,
    module: str,
    *,
    app_name: Optional[str] = None,
    submodule_id: Optional[str] = None,
) -> str:
    """
    Create a doctype folder with Frappe-like files in the given base path.

    Args:
        base_path (str): Path where the doctype folder should be created.
        doc_name (str): Name of the doctype folder.
        doc_id (str): Identifier for the doctype.
        module (str): Module name.

    Returns:
        str: Path to the created doctype folder.
    """
    # Define the default files and their content
    default_files: Dict[str, str] = {
        f"{doc_id}.py": f"""
        """,
        f"{doc_id}.js": f"""

        """,
        f"{doc_id}.json": f"""
{{
    "doctype": "DocType",
    "default_view": "List",
    "sort_field": "creation",
    "sort_order": "DESC",
    "name": "{doc_name}",
    "module": "{module}",
    "fields": [],
    "permissions": [
        {{
            "role": "System Manager",
            "read": 1,
            "write": 1,
            "create": 1,
            "delete": 1
        }}
    ]
}}
        """,
        f"test_{doc_id}.py": f"""

        """,
    }

    # Legacy bridge path (kept for current migration tooling compatibility)
    legacy_doc_folder_path: str = os.path.join(base_path, "doctype", doc_id)
    os.makedirs(legacy_doc_folder_path, exist_ok=True)

    # 3plug hierarchy path (preferred)
    if submodule_id:
        doc_folder_path = os.path.join(base_path, "submodule", submodule_id, "docs", doc_id)
    else:
        doc_folder_path = os.path.join(base_path, "doc", doc_id)
    os.makedirs(doc_folder_path, exist_ok=True)

    # Create the legacy files
    for filename, content in default_files.items():
        file_path: str = os.path.join(legacy_doc_folder_path, filename)
        with open(file_path, "w") as file:
            file.write(content.strip())  # Remove unnecessary whitespace

    # 3plug doc metadata scaffold
    doc_meta = {
        "doc_id": doc_id,
        "doc_key": doc_id,
        "doc_code": None,
        "doc_title": doc_name,
        "doc_kind": "transaction",
        "status": "draft",
        "classification": {
            "app_id": app_name,
            "module_id": module,
            "submodule_id": submodule_id,
            "doc_role": "primary",
        },
        "allowed_actions": [
            "create",
            "update",
            "delete",
            "void",
            "approve",
            "post",
            "reverse",
            "transfer",
            "close",
            "archive",
            "lock",
            "unlock",
            "split",
            "merge",
            "reclassify",
            "reconcile",
            "report",
            "summarize",
            "audit",
            "track",
        ],
        "schema": {
            "source": "scaffold",
            "fields": [],
            "child_tables": [],
        },
        "frappe_reference": {
            "mapped": False,
            "doctype_name": None,
        },
    }
    with open(os.path.join(doc_folder_path, "doc.json"), "w", encoding="utf-8") as file:
        json.dump(doc_meta, file, indent=2)
        file.write("\n")

    with open(os.path.join(doc_folder_path, "schema.json"), "w", encoding="utf-8") as file:
        json.dump(
            {
                "doc_key": doc_id,
                "schema_version": "1.0.0",
                "source": "3plug_scaffold",
                "fields": [],
                "child_tables": [],
                "validation_rules": [],
                "naming_rule": {"strategy": "series", "pattern": None},
            },
            file,
            indent=2,
        )
        file.write("\n")

    with open(os.path.join(doc_folder_path, "actions.json"), "w", encoding="utf-8") as file:
        json.dump(
            {
                "doc_key": doc_id,
                "actions": doc_meta["allowed_actions"],
                "notes": "Action vocabulary aligned with doc/mapping/doc_actions_model.json",
            },
            file,
            indent=2,
        )
        file.write("\n")

    with open(os.path.join(doc_folder_path, "README.md"), "w", encoding="utf-8") as file:
        file.write(
            f"# {underscore_to_titlecase_main(doc_id)}\n\n"
            "3plug Doc scaffold generated by `3plug new-doc`.\n"
        )

    return doc_folder_path
